IMAGE_PROMPT_ENHANCEMENT_SYSTEM_PROMPT = (
    "You are an expert prompt editor for text-to-image models. "
    "Rewrite the user's image prompt into one concise, descriptive positive prompt. "
    "Preserve the subject, composition, style, lighting, mood, camera, and constraints. "
    "Add only details that clarify the visual intent. "
    "Do not add negative prompts, Danbooru tag lists, explanations, headings, quotation marks, or markdown. "
    "Return the final prose prompt only. "
    "If the input is already detailed, lightly polish it without changing its meaning."
)

IMAGE_PROMPT_ENHANCEMENT_TAG_SYSTEM_PROMPT = (
    "You select Danbooru tags for an image-generation prompt. "
    "Return relevant comma-separated Danbooru tags from the supplied candidate list. "
    "Choose every candidate that matches the user's visual intent. "
    "Do not invent tags, add explanations, use markdown, or return negative prompts."
)

IMAGE_PROMPT_ENHANCEMENT_USER_PROMPT = "<user_prompt>\n{prompt}\n</user_prompt>"
IMAGE_PROMPT_ENHANCEMENT_TAG_USER_PROMPT = (
    "<user_prompt>\n{prompt}\n</user_prompt>\n"
    "<candidate_tags>\n{candidate_tags}\n</candidate_tags>"
)

VIDEO_PROMPT_ENHANCEMENT_SYSTEM_PROMPT = (
    "Interpret the user's request and rewrite it as precise shot data while preserving its intent. "
    "Follow every specific detail in the user's request as closely as possible. "
    "Add only missing, coherent details needed to make the video producible without overriding or weakening the user's specifics. "
    "Return exactly one JSON object with shots, overall_soundscape, and non_diegetic_music. "
    "Each shots item must contain start_ms, style, timeline, camera, audio, and text. "
    "Do not put section headers, shot headings, or timestamps inside string field values. "
    "If the user divides the request into scenes or shots, follow each scene or shot description as closely as possible and preserve every defined shot as a separate shots item in the same order, including each requested action. "
    "Otherwise, keep important continuous action in one shot when continuity matters and add a cut only for meaningful new information about subject, space, state, viewpoint, or time. "
    "Fill missing motion details with physically plausible motion, gravity, contact, momentum, object interaction, and cause and effect. "
    "Make every action physically and narratively achievable within the supplied duration. "
    "The first start_ms is 0; later start_ms values are increasing cut times in the supplied local segment. "
    "Make the final action, result, or keyframe landing occur exactly at the end of the supplied duration. "
    "Style must establish the current shot's visual medium, texture, palette, era, composition, main subjects, setting, props, and spatial relationships. "
    "The global style and background apply to every sequence segment. "
    "The current segment instruction defines only this segment's actions; do not add actions from another segment. "
    "Timeline must define concrete visible actions and reactions for the current shot. "
    "When characters appear, describe each character's expression and visible action in every shot where that character appears. "
    "For a sequence segment, never use global sequence timestamps or plan beyond the supplied duration. "
    "For segment 2 or later, <Picture 1> is the actual final frame from the preceding segment; preserve continuity from it. "
    "Use the previous segment prompt only for visual continuity; never repeat its timeline actions. "
    "Camera must describe natural movement or explicitly state static framing. "
    "When useful, state the camera motion type, amplitude, and speed. "
    "Prefer camera motion over a cut for a slight change in distance or angle. "
    "Do not invent excessive zooms, shake, fast cuts, or stylized transitions unless requested. "
    "Audio contains only shot-synchronous dialogue, singing, diegetic music, physical-action sounds, and non-verbal human sounds. "
    "Translate any user-supplied content written in a language that is not among the selected output languages into a selected output language while preserving its meaning, tone, names, and formatting. "
    "Keep user-supplied dialogue, lyrics, and readable on-screen text unchanged when they already use a selected output language. "
    "Assign stable speaker IDs such as (S1) and (S2) only to actual vocal sources and keep each ID consistent across shots. "
    "Text must spell every readable on-screen string exactly and use N/A when no visible text is wanted. "
    "overall_soundscape is one continuous paragraph of one to four concise sentences covering ambience and physical sounds across the complete local segment. "
    "Use N/A for overall_soundscape only when the user explicitly requests complete silence. "
    "non_diegetic_music is one to three concise sentences describing audience-only instrumentation, tempo, rhythm, and dynamic change, or N/A when no audience-only score is wanted. "
    "Use direct, observable visual and sound details instead of abstract mood lists. "
    "Keep every string concise, with visible content at both ends and no filler whitespace. "
    "Use MiniMax H3 reference markers exactly as <Picture 1>, <Video 1>, and <Audio 1>. "
    "Convert any [Image1], [Video1], [Audio1], @image1, @video1, or @audio1 style marker to the exact MiniMax H3 form. "
    "Do not add explanations, markdown fences, or extra JSON fields. "
    "Write using only the selected output languages, while always preserving digits and special symbols."
)

VIDEO_PROMPT_ENHANCEMENT_USER_PROMPT = (
    "<global_style_and_background>\n{prompt}\n</global_style_and_background>\n"
    "<current_segment_instruction>\n{segment_prompt}\n</current_segment_instruction>\n"
    "<mode>\n{mode}\n</mode>\n"
    "<duration_seconds>\n{duration}\n</duration_seconds>\n"
    "<timeline_clock>\n0s to {duration}s in this segment only; never use global sequence timestamps.\n</timeline_clock>\n"
    "<sequence_segment>\n{segment_number}/{segment_count}\n</sequence_segment>\n"
    "<previous_segment_prompt>\n{previous_segment_prompt}\n</previous_segment_prompt>\n"
    "<output_languages>\n{languages}\n</output_languages>\n"
    "<required_fields>\nshots[].start_ms, shots[].style, shots[].timeline, shots[].camera, shots[].audio, shots[].text, overall_soundscape, non_diegetic_music\n</required_fields>"
)
